repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        files: "'cvx', 'tests'"

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.275'
    hooks:
      - id: ruff
        files: "'cvx', 'tests'"
        args: [ --fix, --exit-non-zero-on-fix]


  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint-fix
        args: [ "--ignore", "book/**/*.md" ]

  # enforcing the use of new python syntax with pyupgrade
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.9.0
    hooks:
      - id: pyupgrade
        files: "'cvx','tests'"

  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: v1.4.1
    hooks:
      - id: mypy
        files: cvx
        args: [ --ignore-missing-imports, --explicit-package-bases ]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.26.2
    hooks:
      - id: check-dependabot
        args: [ "--verbose" ]

      - id: check-github-workflows
        args: ["--verbose"]

  - repo: https://github.com/python-poetry/poetry
    rev: '1.6.1'  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
